name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.softvencefsd.xyz
          username: wvogell@wvogell.softvencefsd.xyz
          password: "softvencefsd_wvogell"
          local-dir: ./path_to_local_files # Adjust this to your local directory
          remote-dir: /public_html/storage # Adjust this to your remote directory path
